<?php
namespace NexausSecureDocs;
if (!defined('ABSPATH')) { exit; }
class Generator {
    private static function get_available_models($provider){
        $models=get_transient('nsd_model_list'); if(is_array($models)&&$models) return $models;
        if($provider==='groq'){ $key=get_option('nsd_groq_api_key',''); if(empty($key)) return []; $resp=wp_remote_get('https://api.groq.com/openai/v1/models',['headers'=>['Authorization'=>'Bearer '.$key]]); }
        else { $key=get_option('nsd_openai_api_key',''); if(empty($key)) return []; $resp=wp_remote_get('https://api.openai.com/v1/models',['headers'=>['Authorization'=>'Bearer '.$key]]); }
        if(is_wp_error($resp)) return []; $data=json_decode(wp_remote_retrieve_body($resp),true); $ids=[]; if(!empty($data['data'])){ foreach($data['data'] as $m){ if(!empty($m['id'])) $ids[]=$m['id']; } }
        if($ids) set_transient('nsd_model_list',$ids,HOUR_IN_SECONDS); return $ids;
    }
    private static function choose_model($provider,$desired){
        $available=self::get_available_models($provider); if($desired && in_array($desired,$available,true)) return $desired;
        $prio_groq=['llama-3.3-70b-specdec','llama-3.2-90b-vision-preview','llama-3.2-11b-vision-preview','llama-3.1-70b','llama-3.1-8b','gemma2-9b-it'];
        $prio_openai=['gpt-4o','gpt-4o-mini','gpt-4.1','gpt-4.1-mini']; $prio=$provider==='groq'?$prio_groq:$prio_openai;
        foreach($prio as $m){ if(in_array($m,$available,true)) return $m; } return $desired ?: ($available[0] ?? ($provider==='groq'?'llama-3.1-8b':'gpt-4o-mini'));
    }
    public static function generate($type,$template,$brand,$industry,$scope){
        $provider=get_option('nsd_ai_provider','groq'); $desired=get_option('nsd_model',''); $model=self::choose_model($provider,$desired);
        $system='You are a UK cybersecurity compliance assistant. Return only the final document in clean HTML. Do not include headings like "Answer", "Reasoning", steps, analysis, or markdown. Begin with an <h1>. Use structured, audit-ready sections and tables. No backticks. No code fences.';
        $prompt='Create a '.$type.' using template slug "'.$template.'" for brand "'.$brand.'" in industry "'.$industry.'". Include scope/context: '.$scope.'. Output strictly HTML only with <h1>, <h2>, <h3>, lists and tables, and a version control table at the end. Do not output any explanation or reasoning text.';
        $body=['model'=>$model,'messages'=>[['role'=>'system','content'=>$system],['role'=>'user','content'=>$prompt]],'temperature'=>0.1];
        if($provider==='groq'){ $key=get_option('nsd_groq_api_key',''); if(empty($key)) return new \WP_Error('nsd_no_key','Groq API key not set.'); $url='https://api.groq.com/openai/v1/chat/completions'; $headers=['Authorization'=>'Bearer '.$key,'Content-Type'=>'application/json']; }
        else { $key=get_option('nsd_openai_api_key',''); if(empty($key)) return new \WP_Error('nsd_no_key','OpenAI API key not set.'); $url='https://api.openai.com/v1/chat/completions'; $headers=['Authorization'=>'Bearer '.$key,'Content-Type'=>'application/json']; }
        $resp=wp_remote_post($url,['headers'=>$headers,'body'=>wp_json_encode($body),'timeout'=>60]); if(is_wp_error($resp)) return $resp;
        $code=wp_remote_retrieve_response_code($resp); $data=json_decode(wp_remote_retrieve_body($resp),true);
        if($code!==200 || empty($data['choices'][0]['message']['content'])){ $msg=!empty($data['error']['message'])?$data['error']['message']:'Generation failed. Check API key, provider, or model.'; return new \WP_Error('nsd_api_error',$msg); }
        $html=$data['choices'][0]['message']['content'];
        $html=preg_replace('/```[\s\S]*?```/m','',$html); $pos=strpos($html,'<'); if($pos!==false){ $html=substr($html,$pos); }
        $allowed=wp_kses_allowed_html('post'); $clean=wp_kses($html,$allowed); $clean.='<hr><p style="font-size:12px;color:#666">Generated by Nexaus SecureDocs. Review for accuracy before use.</p>'; return $clean;
    }
}